apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: retail_pg
    url: postgres:5432
    database: retail_db
    user: postgres
    secureJsonData:
      password: admin
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
